### ISSUE TITLE
Android issue: HttpClient was deprecated in API Level 22 and removed in API Level 23

### ISSUE THREAD

**Issue by basst85** [bunq/sdk_java#69] opened 2018-01-17 20:56 UTC
The dependency "org.apache.httpcomponents.httpclient" is removed from API level 23+
Maybe a other HttpClient can be used, like "OkHttp"?

## Steps to reproduce:
1. Use SDK in app on Android 8.0

## What happens:
I get this error when executing ApiContext.create:

`java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)
  at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
  at com.bunq.sdk.http.ApiClient.buildHttpClient(ApiClient.java:120)
  at com.bunq.sdk.http.ApiClient.<init>(ApiClient.java:113)
  at com.bunq.sdk.model.core.Installation.create(Installation.java:43)
  at com.bunq.sdk.context.ApiContext.initializeInstallation(ApiContext.java:173)
  at com.bunq.sdk.context.ApiContext.initialize(ApiContext.java:163)
  at com.bunq.sdk.context.ApiContext.create(ApiContext.java:127)
  at com.bunq.sdk.context.ApiContext.create(ApiContext.java:109)
  at com.bunq.sdk.context.ApiContext.create(ApiContext.java:101)`

## Traceback
[//]: # (If there is a traceback please share it in a quote! You can do this by pasting the traceback text, highlighting it and pressing the quote button.)

## SDK version and environment
- Tested on [0.12.4](https://github.com/bunq/sdk_java/releases/tag/0.12.4)
- [x] Sandbox

## Response id
[//]: # (If this error has something to do with a request that fails, please provide the response id of the request.)
- Response id:

## Extra info:
[//]: # (Please provide any other relevant information here)

**Comment by OGKevin** [comment] 2018-01-18 08:13
Thanks for reporting.

If thats the case, that this is related to bunq/sdk_java#25 and should be fixed in the 0.12.5 release!

Duplicate of bunq/sdk_java#25

**Comment by basst85** [comment] 2018-01-18 08:22
You're right, this issue is a bit a duplicate of #25. Sorry for that :-)

**Comment by OGKevin** [comment] 2018-01-18 08:24
@basst85 no problem at all :thumbsup: more reason to release 0.12.5! 

Im closing this issue then.

**Comment by OGKevin** [comment] 2018-05-03 18:14
Closing due to #25

**Closed by OGKevin** 2018-05-03 18:14 UTC
